former_students_home:
  path: /
  defaults: { _controller: FormerStudentsBundle:Bac:index}

former_students_inscription:
  path: /inscription
  defaults: { _controller: FormerStudentsBundle:Bac:inscription}


former_students_list:
    path:  /list/{page}
    defaults: { _controller: FormerStudentsBundle:Bac:list, page: 1 }

former_students_documentation:
  path: /documentation
  defaults: { _controller: FormerStudentsBundle:Bac:documentation}


former_students_documentation_program:
  path: /documentation/{annee}/{section}/{matiere}
  defaults: { _controller: FormerStudentsBundle:Bac:documentationProgram}